### ISSUE TITLE
Unexpected keyword argument 'type'

### ISSUE THREAD

**Issue by Nordmole** [coldfix/certbot-dns-netcup#22] opened 2023-09-03 12:38 UTC
Hello,

I've noticed an error when using this plugin! The full CLI output is as follows:

```bash
bug@github:~$ sudo certbot certonly --authenticator dns-netcup --dns-netcup-credentials /root/.secrets/d
omain-credentials.ini --dns-netcup-propagation-seconds 900 --non-interactive -d *.censor.ed --key-type ecdsa
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator dns-netcup, Installer None
Requesting a certificate for *.censor.ed
Performing the following challenges:
dns-01 challenge for censor.ed
Cleaning up challenges
Encountered exception during recovery: TypeError: delete_record() got an unexpected keyword argument 'type'
An unexpected error occurred:
TypeError: create_record() got an unexpected keyword argument 'type'
Please see the logfiles in /var/log/letsencrypt for more details.
```

What is going on? My certbot version is **certbot 1.12.0** and my server is running **Debian 11**.

**Comment by coldfix** [comment] 2023-09-11 22:33
Likely a duplicate of #11. Workaround was to pin a compatible version of dns-lexicon. `pip install dns-lexicon==3.5`. Otherwise try using the docker image instead. That version of certbot is ancient by now.

**Comment by coldfix** [comment] 2023-09-11 22:34
LMK if that works.

**Closed by coldfix** 2023-09-11 22:34 UTC

**Comment by Nordmole** [comment] 2023-09-18 15:01
It works! Thx!
